#!/usr/bin/env python3
"""Vendor the MLX-DLSS PyTorch inference path and its weight tools into the pack.

Upstream — <https://github.com/iamwavecut/MLX-DLSS>, Apache-2.0 — is a Swift and
MLX project first, with a Python package beside it that runs the same recovered
graph on any machine through PyTorch. Only the half of that package this pack
runs is taken: the first-frame and temporal inference (`features`, `composition`,
`model`, `pipeline`, `temporal`, the `weight_spec.json` the loader validates
against) and the two modules that turn the user's own DLL into those weights
(`tools/extract_dlssnr_weights.py`, `tools/unpack_dlssnr_weights.py`). The web
front end, the video CLI, frame generation, the Metal packager and the Core ML
converter are its product and its other backends, and stay upstream.
`mlxdlss/__init__.py` says why this is copied rather than installed, and is
written by hand — this script never touches it.

Re-syncing:

    git clone https://github.com/iamwavecut/MLX-DLSS /tmp/mlxdlss
    git -C /tmp/mlxdlss checkout <commit>
    python3 tools/vendor_mlxdlss.py /tmp/mlxdlss
    COMFYUI_PATH=~/ComfyUI <comfy-venv>/bin/python3 tests/test_neural_fake.py tests/test_mlxdlss_vendor.py

**Local deltas are re-applied, not re-invented**, on the h3lora rule: edits to
the copy are held as a patch (`tools/mlxdlss.patch`, regenerated by `--save`)
and applied after the copy. A hunk that no longer applies is a hard error —
upstream has changed the code a fix sits on, which is the moment somebody has to
look at whether the fix is still needed.

    python3 tools/vendor_mlxdlss.py --save     # local edits -> tools/mlxdlss.patch

The revision is stamped into `__init__.py`'s docstring and into its `REVISION`
constant, which is what the settings page prints.
"""

import argparse
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "creator", "mlxdlss")
PATCH = os.path.join(ROOT, "tools", "mlxdlss.patch")
HEADER = os.path.join(OUT, "__init__.py")

UPSTREAM = "iamwavecut/MLX-DLSS"

# Source path under the clone -> file name in the copy. The tools lose their
# `tools/` directory because neither imports anything relatively, and one flat
# package is one fewer place for a re-sync to get a path wrong.
FILES = {
    "python/mlxdlss/features.py": "features.py",
    "python/mlxdlss/composition.py": "composition.py",
    "python/mlxdlss/model.py": "model.py",
    "python/mlxdlss/pipeline.py": "pipeline.py",
    "python/mlxdlss/temporal.py": "temporal.py",
    "python/mlxdlss/weight_spec.json": "weight_spec.json",
    "python/mlxdlss/tools/extract_dlssnr_weights.py": "extract_dlssnr_weights.py",
    "python/mlxdlss/tools/unpack_dlssnr_weights.py": "unpack_dlssnr_weights.py",
}


def revision(clone, short=True):
    try:
        out = subprocess.run(["git", "-C", clone, "rev-parse"] + (["--short"] if short else []) + ["HEAD"],
                             capture_output=True, text=True, check=True)
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def date(clone):
    try:
        out = subprocess.run(["git", "-C", clone, "log", "-1", "--format=%cs"],
                             capture_output=True, text=True, check=True)
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def save_patch():
    diff = subprocess.run(
        ["git", "-C", ROOT, "diff", "--", "creator/mlxdlss"],
        capture_output=True, text=True, check=True).stdout
    if not diff.strip():
        sys.exit("nothing to save: creator/mlxdlss/ has no uncommitted changes")
    with open(PATCH, "w", encoding="utf-8") as handle:
        handle.write(diff)
    print(f"wrote {os.path.relpath(PATCH, ROOT)} ({len(diff.splitlines())} lines)")


def stamp(short, full, when):
    """Rewrite the revision line and the constant in the hand-written init."""
    with open(HEADER, "r", encoding="utf-8") as handle:
        text = handle.read()
    stamped, count = re.subn(
        r"revision `[^`]+` \([^)]*\)", f"revision `{short}` ({when})", text, count=1)
    stamped, count2 = re.subn(
        r'^REVISION = "[0-9a-f]*"$', f'REVISION = "{full}"', stamped, count=1, flags=re.M)
    if not count or not count2:
        sys.exit(f"{HEADER} no longer carries a revision line and a REVISION constant to stamp")
    with open(HEADER, "w", encoding="utf-8") as handle:
        handle.write(stamped)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("clone", nargs="?", help="path to a clone of " + UPSTREAM)
    parser.add_argument("--save", action="store_true",
                        help="write the current local edits to tools/mlxdlss.patch")
    args = parser.parse_args()

    if args.save:
        save_patch()
        return
    if not args.clone:
        parser.error("a path to an upstream clone is required")
    if not os.path.isdir(os.path.join(args.clone, "python", "mlxdlss")):
        sys.exit(f"{args.clone} has no python/mlxdlss — point this at the clone's root")

    os.makedirs(OUT, exist_ok=True)
    for source, name in FILES.items():
        src = os.path.join(args.clone, source)
        if not os.path.isfile(src):
            sys.exit(f"upstream no longer ships {source} — check what replaced it")
        with open(src, "rb") as handle:
            body = handle.read()
        with open(os.path.join(OUT, name), "wb") as handle:
            handle.write(body)
        print(f"copied {source} -> mlxdlss/{name}")

    for name in ("LICENSE", "NOTICE"):
        src = os.path.join(args.clone, name)
        if os.path.isfile(src):
            with open(src, "rb") as handle:
                body = handle.read()
            with open(os.path.join(OUT, name), "wb") as handle:
                handle.write(body)
            print(f"copied {name}")

    if os.path.isfile(PATCH):
        result = subprocess.run(["git", "-C", ROOT, "apply", "--verbose", PATCH],
                                capture_output=True, text=True)
        if result.returncode:
            sys.exit(
                f"{os.path.relpath(PATCH, ROOT)} no longer applies:\n{result.stderr}\n"
                "Upstream has changed the code a local fix sits on. Read the "
                "hunks — most likely upstream has made the fix themselves and "
                "the local one should be dropped from the patch.")
        print(f"applied {os.path.relpath(PATCH, ROOT)}")

    short, full, when = revision(args.clone), revision(args.clone, short=False), date(args.clone)
    stamp(short, full, when)
    print(f"stamped {UPSTREAM} @ {short} ({when})")


if __name__ == "__main__":
    main()
