#!/usr/bin/env python3
"""Vendor the H3-safe LoRA library into the pack.

Upstream — <https://github.com/cicalooo/ComfyUI-H3-PowerLoraStack>, Apache-2.0 —
ships four nodes and a web UI around one library. Only the library is taken:
`h3lora/*.py` minus `nodes.py`, `server.py` and `detect.py`, which are its
product rather than its arithmetic. `h3lora/__init__.py` argues why this is
copied rather than called at all, and is written by hand — this script never
touches it.

Re-syncing:

    git clone --depth 1 https://github.com/cicalooo/ComfyUI-H3-PowerLoraStack /tmp/h3pls
    python3 tools/vendor_h3lora.py /tmp/h3pls
    COMFYUI_PATH=~/ComfyUI <comfy-venv>/bin/python3 tests/test_h3lora.py

**Local deltas are re-applied, not re-invented.** This copy carries a handful of
fixes to open findings in upstream's own audit, each marked `# MMC:` at its
site. They are held as a patch (`tools/h3lora.patch`, regenerated by `--save`)
and applied after the copy. A hunk that no longer applies is a hard error and
not a warning: it means upstream has changed that code, which is exactly the
moment somebody has to look at whether the fix is still needed — most likely
because upstream has made it themselves.

    python3 tools/vendor_h3lora.py --save     # local edits -> tools/h3lora.patch

The revision is stamped into `__init__.py`'s docstring, which is what makes "is
our copy current?" answerable by reading one line.
"""

import argparse
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "h3lora")
PATCH = os.path.join(ROOT, "tools", "h3lora.patch")
HEADER = os.path.join(OUT, "__init__.py")

UPSTREAM = "cicalooo/ComfyUI-H3-PowerLoraStack"

# The library, and only the library. `apply.py` imports all six of the others.
MODULES = ("adaln.py", "apply.py", "branch.py", "gain.py", "keymap.py",
           "modality.py", "schedule.py")


def revision(clone):
    """The upstream revision of `clone`, short, or "unknown" outside a repo."""
    try:
        out = subprocess.run(["git", "-C", clone, "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True, check=True)
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def date(clone):
    try:
        out = subprocess.run(["git", "-C", clone, "log", "-1", "--format=%cs"],
                             capture_output=True, text=True, check=True)
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def save_patch():
    """The working tree's deltas against the last vendored copy -> the patch.

    Run after fixing something in `h3lora/` by hand, so the fix survives the
    next re-sync. Diffed against HEAD rather than against a fresh clone: what is
    wanted is *our* changes, and the committed copy is upstream's plus them.
    """
    diff = subprocess.run(
        ["git", "-C", ROOT, "diff", "--", "h3lora"],
        capture_output=True, text=True, check=True).stdout
    if not diff.strip():
        sys.exit("nothing to save: h3lora/ has no uncommitted changes")
    with open(PATCH, "w", encoding="utf-8") as handle:
        handle.write(diff)
    print(f"wrote {os.path.relpath(PATCH, ROOT)} ({len(diff.splitlines())} lines)")


def stamp(rev, when):
    """Rewrite the revision line in the vendored package's own docstring."""
    with open(HEADER, "r", encoding="utf-8") as handle:
        text = handle.read()
    stamped, count = re.subn(
        r"revision `[^`]+` \([^)]*\)",
        f"revision `{rev}` ({when})",
        text, count=1)
    if not count:
        sys.exit(f"{HEADER} no longer carries a revision line to stamp")
    with open(HEADER, "w", encoding="utf-8") as handle:
        handle.write(stamped)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("clone", nargs="?",
                        help="path to a clone of " + UPSTREAM)
    parser.add_argument("--save", action="store_true",
                        help="write the current local edits to tools/h3lora.patch")
    args = parser.parse_args()

    if args.save:
        save_patch()
        return
    if not args.clone:
        parser.error("a path to an upstream clone is required")

    source = os.path.join(args.clone, "h3lora")
    if not os.path.isdir(source):
        sys.exit(f"{source} is not a directory — point this at the clone's root")

    for name in MODULES:
        src = os.path.join(source, name)
        if not os.path.isfile(src):
            sys.exit(f"upstream no longer ships h3lora/{name} — check what replaced it")
        with open(src, "r", encoding="utf-8") as handle:
            body = handle.read()
        with open(os.path.join(OUT, name), "w", encoding="utf-8") as handle:
            handle.write(body)
        print(f"copied h3lora/{name}")

    for name in ("LICENSE", "NOTICE"):
        src = os.path.join(args.clone, name)
        if os.path.isfile(src):
            with open(src, "r", encoding="utf-8") as handle:
                body = handle.read()
            with open(os.path.join(OUT, name), "w", encoding="utf-8") as handle:
                handle.write(body)
            print(f"copied {name}")

    if os.path.isfile(PATCH):
        result = subprocess.run(["git", "-C", ROOT, "apply", "--verbose", PATCH],
                                capture_output=True, text=True)
        if result.returncode:
            sys.exit(
                f"{os.path.relpath(PATCH, ROOT)} no longer applies:\n{result.stderr}\n"
                "Upstream has changed the code a local fix sits on. Read the "
                "hunks — most likely upstream has made the fix themselves and "
                "the local one should be dropped from the patch."
            )
        print(f"applied {os.path.relpath(PATCH, ROOT)}")

    rev, when = revision(args.clone), date(args.clone)
    stamp(rev, when)
    print(f"stamped {UPSTREAM} @ {rev} ({when})")


if __name__ == "__main__":
    main()
