#!/usr/bin/env python3
"""Vendor the ComfyUI-VDN-H3 port's library into the pack.

Upstream — <https://github.com/Saganaki22/ComfyUI-VDN-H3>, Apache-2.0 — is a
port of OpenVDN's Video Delta Net hybrid attention onto ComfyUI's own MiniMax-H3
model: runtime patches over a loaded MODEL, the released checkpoints re-keyed in
memory, no core file touched and no package beyond torch. Only its library is
taken — the checkpoint reader, the adapter conversion, the LoRA application, the
linear branch, the windowed softmax and the forward that ties them — plus
`nodes.py`, which is half library: `_apply_vdn` is the one function that
assembles a patched model from a stage directory, and it is what
`creator/vdn.py` calls. The two node classes in that file are upstream's product
and are never registered here; the example workflow, the int8 quantizer and
upstream's test suite stay upstream. `vdnh3/__init__.py` says why this is copied
rather than installed, and is written by hand — this script never touches it.

**Imports are re-rooted, not patched.** Upstream addresses itself as the
top-level package `vdn_h3`, which is what a custom node folder is to ComfyUI;
here it is a sub-package of `creator`, so every `from vdn_h3.x import` becomes
`from .x import` as the file is copied. A mechanical rewrite rather than a hunk
in the patch file, because the patch would then break on every upstream change
near an import line for a reason that has nothing to do with the code.

Re-syncing:

    git clone https://github.com/Saganaki22/ComfyUI-VDN-H3 /tmp/vdnh3
    git -C /tmp/vdnh3 checkout <commit>
    python3 tools/vendor_vdnh3.py /tmp/vdnh3
    COMFYUI_PATH=~/ComfyUI <comfy-venv>/bin/python3 tests/test_vdnh3_vendor.py

**Local deltas are re-applied, not re-invented**, on the h3lora rule: edits to
the copy are held as a patch (`tools/vdnh3.patch`, regenerated by `--save`) and
applied after the copy. A hunk that no longer applies is a hard error —
upstream has changed the code a fix sits on, which is the moment somebody has to
look at whether the fix is still needed. There is no patch file until there is
a delta to hold.

    python3 tools/vendor_vdnh3.py --save     # local edits -> tools/vdnh3.patch

The revision is stamped into `__init__.py`'s docstring and into its `REVISION`
constant, which is what the settings page prints.
"""

import argparse
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "creator", "vdnh3")
PATCH = os.path.join(ROOT, "tools", "vdnh3.patch")
HEADER = os.path.join(OUT, "__init__.py")

UPSTREAM = "Saganaki22/ComfyUI-VDN-H3"

# The library, and only the library — see the module docstring for `nodes.py`.
MODULES = ("spec.py", "adapters.py", "apply.py", "branch.py", "window.py",
           "hybrid.py", "nodes.py")

# `vdn_h3` as upstream spells itself -> this package, relatively. Anchored at
# a line's indentation so the lazy imports inside functions are re-rooted too.
REROOT = (
    (re.compile(r"^(\s*)from vdn_h3\.(\w+) import", re.M), r"\1from .\2 import"),
    (re.compile(r"^(\s*)from vdn_h3 import", re.M), r"\1from . import"),
    (re.compile(r"^(\s*)import vdn_h3\.(\w+) as (\w+)", re.M), r"\1from . import \2 as \3"),
)


def reroot(text):
    """Upstream's absolute imports as this package's relative ones."""
    for pattern, replacement in REROOT:
        text = pattern.sub(replacement, text)
    if re.search(r"^\s*(from|import) vdn_h3\b", text, re.M):
        raise SystemExit("an upstream import shape this script does not know how "
                         "to re-root — add it to REROOT")
    return text


def revision(clone, short=True):
    try:
        out = subprocess.run(["git", "-C", clone, "rev-parse"] + (["--short"] if short else []) + ["HEAD"],
                             capture_output=True, text=True, check=True)
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def date(clone):
    try:
        out = subprocess.run(["git", "-C", clone, "log", "-1", "--format=%cs"],
                             capture_output=True, text=True, check=True)
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def save_patch():
    diff = subprocess.run(
        ["git", "-C", ROOT, "diff", "--", "creator/vdnh3"],
        capture_output=True, text=True, check=True).stdout
    if not diff.strip():
        sys.exit("nothing to save: creator/vdnh3/ has no uncommitted changes")
    with open(PATCH, "w", encoding="utf-8") as handle:
        handle.write(diff)
    print(f"wrote {os.path.relpath(PATCH, ROOT)} ({len(diff.splitlines())} lines)")


def stamp(short, full, when):
    """Rewrite the revision line and the constant in the hand-written init."""
    with open(HEADER, "r", encoding="utf-8") as handle:
        text = handle.read()
    stamped, count = re.subn(
        r"revision `[^`]+` \([^)]*\)", f"revision `{short}` ({when})", text, count=1)
    stamped, count2 = re.subn(
        r'^REVISION = "[0-9a-f]*"$', f'REVISION = "{full}"', stamped, count=1, flags=re.M)
    if not count or not count2:
        sys.exit(f"{HEADER} no longer carries a revision line and a REVISION constant to stamp")
    with open(HEADER, "w", encoding="utf-8") as handle:
        handle.write(stamped)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("clone", nargs="?", help="path to a clone of " + UPSTREAM)
    parser.add_argument("--save", action="store_true",
                        help="write the current local edits to tools/vdnh3.patch")
    args = parser.parse_args()

    if args.save:
        save_patch()
        return
    if not args.clone:
        parser.error("a path to an upstream clone is required")
    src_dir = os.path.join(args.clone, "vdn_h3")
    if not os.path.isdir(src_dir):
        sys.exit(f"{args.clone} has no vdn_h3/ — point this at the clone's root")

    os.makedirs(OUT, exist_ok=True)
    for name in MODULES:
        src = os.path.join(src_dir, name)
        if not os.path.isfile(src):
            sys.exit(f"upstream no longer ships vdn_h3/{name} — check what replaced it")
        with open(src, "r", encoding="utf-8") as handle:
            body = reroot(handle.read())
        with open(os.path.join(OUT, name), "w", encoding="utf-8") as handle:
            handle.write(body)
        print(f"copied vdn_h3/{name} -> vdnh3/{name}")

    src = os.path.join(args.clone, "LICENSE")
    if not os.path.isfile(src):
        sys.exit("upstream ships no LICENSE — the copy cannot travel without one")
    with open(src, "rb") as handle:
        body = handle.read()
    with open(os.path.join(OUT, "LICENSE"), "wb") as handle:
        handle.write(body)
    print("copied LICENSE")

    if os.path.isfile(PATCH):
        result = subprocess.run(["git", "-C", ROOT, "apply", "--verbose", PATCH],
                                capture_output=True, text=True)
        if result.returncode:
            sys.exit(
                f"{os.path.relpath(PATCH, ROOT)} no longer applies:\n{result.stderr}\n"
                "Upstream has changed the code a local fix sits on. Read the "
                "hunks — most likely upstream has made the fix themselves and "
                "the local one should be dropped from the patch.")
        print(f"applied {os.path.relpath(PATCH, ROOT)}")

    short, full, when = revision(args.clone), revision(args.clone, short=False), date(args.clone)
    stamp(short, full, when)
    print(f"stamped {UPSTREAM} @ {short} ({when})")


if __name__ == "__main__":
    main()
